Plant Epic Issue Template
TRICERA-energy/.github pull request #2
Opened 2024-02-23 14:09 UTC by Tricera-Manuel-Kersic

Introduce plant epic issue template for an overview (!) of all tasks coming up for a battery plant and to track its progress

2024-02-23 14:11 UTC, Tricera-Manuel-Kersic commented
This is the list that came up in my mind and my experience of planning and commissioning our battery plants. You all have different views on theses processes and I would like to have a good (and possibly generic) overview template that includes most of the tasks for all of us. Would be great if you could try to find major gaps (not too detailed)) in this list related to your tasks so far.

2024-03-05 10:51 UTC, Tricera-Hendrik-Weiss requested changes

2024-03-05 10:51 UTC, Tricera-Hendrik-Weiss commented on .github/ISSUE_TEMPLATE/plant-epic.md
> +- [ ] Create network plan
```suggestion
- [ ] Create network plan
- [ ] Select hardware
```
We are running into trouble (redundancy tasks, steag/SENS fiber optics, ...)  a lot as we don't have a network plan when ordering hardware.

2024-03-05 10:51 UTC, Tricera-Hendrik-Weiss commented on .github/ISSUE_TEMPLATE/plant-epic.md
> +- [ ] Configure router
```suggestion
- [ ] Configure router
  - [ ] Setup login credentials
  - [ ] Setup IP address
  - [ ] Setup DHCP Server
  - [ ] Setup wireguard VPN configuration
```

2024-03-05 10:51 UTC, Tricera-Hendrik-Weiss commented on .github/ISSUE_TEMPLATE/plant-epic.md
> +- [ ] Check grafana
```suggestion
- [ ] Configure server
  - [ ] Setup IP address of OS and IPMI
  - [ ] Setup kubernetes cluster
  - [ ] Rollout: MetalLB, Traefik, Prometheus, Loki, MariaDB, EMQX, Grafana, InfluxDB, Telegraf
  - [ ] Rollout: ESF
  - [ ] Rollout: BCC
  - [ ] Rollout: EMS
  - [ ] Check datalogging in influx
  - [ ] Check grafana access
  - [ ] Optional: Setup Customer specific alerts
```

2024-03-15 14:01 UTC, Tricera-Paul-Klotsche requested changes

2024-03-15 14:01 UTC, Tricera-Paul-Klotsche commented on .github/ISSUE_TEMPLATE/plant-epic.md
> +- [ ] Select hardware
```suggestion
- [ ] Collect SW related requirements from offer, contract and other binding documents
- [ ] Select hardware
```

2024-03-15 14:01 UTC, Tricera-Paul-Klotsche commented on .github/ISSUE_TEMPLATE/plant-epic.md
> +- [ ] Agree on customer control interface (if necessary)
```suggestion
- [ ] Agree on customer control interface (if necessary)
- [ ] Agree on interface to site periphery, i.e. fire detection, building management system (DE: GLT) (if necessary)
```

2024-03-15 14:01 UTC, Tricera-Paul-Klotsche commented on .github/ISSUE_TEMPLATE/plant-epic.md
> +- [ ] ...
```suggestion
- [ ] Order PPC with project specific requirements
- [ ] ...
```

2024-03-15 14:01 UTC, Tricera-Paul-Klotsche commented on .github/ISSUE_TEMPLATE/plant-epic.md
> +- [ ] Check communication with smartblue router and the ppc
```suggestion
- [ ] Check communication with smartblue router and the ppc
- [ ] Configure Inverters according to E.9
- [ ] Check mapping of SGs and inverters in BCC. 
- [ ] Test attaching all SGs and inverter
- [ ] Perform power test (attach and apply some power via bcc)
```

2024-03-15 14:01 UTC, Tricera-Paul-Klotsche commented on .github/ISSUE_TEMPLATE/plant-epic.md
> +- [ ] Perform power test (attach and apply some power via bcc)
```suggestion
```

2024-03-15 14:01 UTC, Tricera-Paul-Klotsche commented on .github/ISSUE_TEMPLATE/plant-epic.md
> +  - [ ] network operator (mostly smartblue's part)
```suggestion
  - [ ] network operator ("Bittest") (mostly smartblue's part)
```

2024-03-15 14:01 UTC, Tricera-Paul-Klotsche commented on .github/ISSUE_TEMPLATE/plant-epic.md
> +- [ ] Test whole control chain, possibly with smartblue (e.g. marketer/network operator -> ems -> ppc -> bcc)
```suggestion
- [ ] Configure PPC according to E.9
- [ ] Test whole control chain, possibly with smartblue (e.g. marketer/network operator -> ems -> ppc -> bcc)
- [ ] Functional test with network operator
```

2024-03-15 14:01 UTC, Tricera-Paul-Klotsche commented on .github/ISSUE_TEMPLATE/plant-epic.md
> +- [ ] Run double hump test (*Doppelhöckertest*) (if necessary)
```suggestion
- [ ] FCR: Run double hump test (*Doppelhöckertest*) and 4h test (if necessary)
- [ ] Compliance test ("Konformitätstest") 
- [ ] Handover to O&M / customer, documentation
```

2024-03-20 15:53 UTC, merged